main:
  blockcreative: true
perm:
  mine: 'mte.miningmoney'
msg:
  EMERALD_ORE: '&2MineToEarn &8» &6+150 coins &f(Emerald ore broken)'
  DIAMOND_ORE: '&2MineToEarn &8» &6+120 coins &f(Diamond ore broken)'
  REDSTONE_ORE: '&2MineToEarn &8» &6+100 coins &f(Redstone ore broken)'
  GOLD_ORE: '&2MineToEarn &8» &6+80 coins &f(Gold ore broken)'
  IRON_ORE: '&2MineToEarn &8» &6+50 coins &f(Iron ore broken)'
  COAL_ORE: '&2MineToEarn &8» &6+30 coins &f(Coal ore broken)'
  LAPIS_ORE: '&2MineToEarn &8» &6+10 coins &f(Lapis ore broken)'
  QUARTZ_ORE: '&2MineToEarn &8» &6+10 coins &f(Quartz ore broken)'
pay:
  EMERALD_ORE: 150
  DIAMOND_ORE: 120
  REDSTONE_ORE: 100
  GOLD_ORE: 80
  IRON_ORE: 50
  COAL_ORE: 30
  LAPIS_ORE: 10
  QUARTZ_ORE: 10